ccflags-y += -DUACPI_OVERRIDE_LIBC
ccflags-y += -DUACPI_OVERRIDE_TYPES
ccflags-y += -DUACPI_FORMATTED_LOGGING
ccflags-y += -DUACPI_KERNEL_INITIALIZATION
ccflags-y += -march=x86-64-v2

obj-y += \
	glue.o \
	source/tables.o \
	source/types.o \
	source/uacpi.o \
	source/utilities.o \
	source/interpreter.o \
	source/opcodes.o \
	source/namespace.o \
	source/stdlib.o \
	source/shareable.o \
	source/opregion.o \
	source/default_handlers.o \
	source/io.o \
	source/notify.o \
	source/sleep.o \
	source/registers.o \
	source/resources.o \
	source/event.o \
	source/mutex.o \
	source/osi.o
